# <center>Arrays for Scientific Computation</center>
References:
* https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
* http://cs231n.github.io/python-numpy-tutorial/#numpy
* https://docs.scipy.org/doc/scipy/reference/sparse.html
* https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/

## 1. Numpy
- Numpy is the core library for scientific computing in Python. It provides high-performance multidimensional array objects, and tools for working with these arrays. 

- A numpy **array** is a grid of values, usually of the same type, although technically you can store values of different types (this may complicate array operation). 
    - The number of dimensions is the **rank** of the array
    - The **shape** of an array is a tuple of integers giving the size of the array along each dimension
    - Numpy arrays can be initialized from nested Python lists, and access elements using square brackets

In [2]:
# enable interactiveShell
# so that Jupyter will display variables or 
# unassigned output of a statement 
# without the need for a print statement

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# import numpy package
import numpy as np


In [2]:
# Exercise 1.1. Initialize an array from list

# Create a rank 1 array
a = np.array([1, 2, 3])  

print ("data type:", type(a))
print("array shape, ",a.shape)
print("the first element:", a[0])

# Change an element of the array
a[0] = 5                 
a

data type: <class 'numpy.ndarray'>
array shape,  (3,)
the first element: 1


array([5, 2, 3])

In [3]:
# Exercise 1.2. Create a rank 2 array from list of lists

b = np.array([[1,2,3],[4,5,6]])   
b

print ("b's shape:", b.shape)                   
print("value at (0,0): ", b[0, 0])
print("value at (1,2): ", b[1, 2])     

array([[1, 2, 3],
       [4, 5, 6]])

b's shape: (2, 3)
value at (0,0):  1
value at (1,2):  6


In [4]:
# Exercise 1.3. Create a rank 2 array of all zeros

a = np.zeros((2,2))  
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [5]:
# Exercise 1.4. Create a rank 2 array of all ones

b = np.ones((3,2))   
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [6]:
# Exercise 1.5. Create a constant array

c = np.full((2,2), 7) 
c

array([[7, 7],
       [7, 7]])

In [7]:
# Exercise 1.6. a 2x2 identity matrix

d = np.eye(2)        
d

array([[ 1.,  0.],
       [ 0.,  1.]])

In [8]:
# Exercise 1.7. # Create a matrix filled with random values

# random returns random floats within [0, 1.0)
e = np.random.random((2,2)) 
e

# randint(low, high, size): random integer
np.random.randint(1, 6, (4,5))

# randn(d0, d1, ...dn): random floats from normal distribution 
np.random.randn(4,3,2)

array([[ 0.04177747,  0.8233474 ],
       [ 0.16618748,  0.51203548]])

array([[3, 5, 3, 2, 2],
       [4, 2, 4, 5, 3],
       [2, 2, 4, 2, 1],
       [1, 1, 2, 4, 5]])

array([[[ 1.3471418 , -1.15716998],
        [-0.30961648,  0.73155703],
        [ 0.65633238, -1.57421335]],

       [[ 0.30654684, -0.55508745],
        [ 0.56175375,  0.08125419],
        [-0.12771665, -0.94662242]],

       [[ 0.12425935, -0.81744982],
        [-1.66029442, -0.15979185],
        [ 1.04720451,  1.13550326]],

       [[ 0.73634776,  1.05070395],
        [-0.0967209 , -2.1548387 ],
        [-0.89693619,  1.15879627]]])

### 1.1. Array Slicing
 - **Similar to Python lists, numpy arrays can be sliced**. 
 - Since arrays may be multidimensional, you must **specify a slice for each dimension of the array**
 - **A slice of an array is a view into the same data**, so modifying it will modify the original array.

In [9]:
# Exercise 1.1.1 Get a specific row

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# get the first row
row_1=a[0]      
# row_1[0,:] does the same too

print("the first row:", row_1)
print("shape of 1st row:", row_1.shape)

# loop through all rows
for idx,row in enumerate(a):
    print(idx, row)


the first row: [1 2 3 4]
shape of 1st row: (4,)
0 [1 2 3 4]
1 [5 6 7 8]
2 [ 9 10 11 12]


In [10]:
# Exercise 1.1.2 Get a specific column

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# get the first column
column_1=a[:, 0]      
print("the first column:", column_1)
print("shape of 1st column:", column_1.shape)

the first column: [1 5 9]
shape of 1st column: (3,)


In [11]:
# Exercise 1.1.3 Get subarrays

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

# Use slicing to pull out the subarray 
# consisting of the first 2 rows
# and columns 1 and 2 

b = a[:2, 1:3]
b


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[2, 3],
       [6, 7]])

In [19]:
# Exercise 1.1.4 

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 1. Get subset of "a" consisting of
#    the 1st & 3rd rows and
#    the 1st & 2nd columns
a
a[[0,2], 0:2]

# 2. get the last two rows and last two columns
a[-2:, -2:]
# 3. Reverse the order of columns, i.e. the first column becomes the last
a[:, ::-1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

array([[ 1,  2],
       [ 9, 10]])

array([[ 7,  8],
       [11, 12]])

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [ ]:
# Exercise 1.1.5: Modify slice

# A slice of an array is **a view into the same data**, 
# so modifying it will modify the original array.

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# b is a slice
b = a[:2, 1:3]

print ("Original value at (0,1):", a[0, 1])  
b[0, 0] = 77    

# b[0, 0] is the same piece of data as a[0, 1]
print ("Modified value at (0,1):", a[0, 1])  

# how to avoid modify the original array? 
b1=np.copy(b)
b1[0,0]=100
a


### 1.2. Boolean array indexing (Selection by conditions)

- Boolean array indexing lets you pick out arbitrary elements of an array. 
- Frequently this type of indexing is used to select elements of an array that satisfy some conditions. 
- Typically it's used with function **np.where**

In [ ]:
# Exercise 1.2.1: boolean array indexing

a = np.array([[1,2], [3, 4], [5, 6]])

# Find the elements of "a" that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where value tells
# whether that element of a is > 2

bool_idx = (a > 2)  

bool_idx

In [ ]:
# Exercise 1.2.2: Select values >2

print (a[bool_idx])

# We can do all of the above in a single concise statement:
print (a[a > 2])
# note the result is 1-dimension array

In [ ]:
# Exercise 1.2.3: Find locations where value>2

a = np.array([[1,2], [3, 4], [5, 6]])

# np.where returns the locations 
# satisfying the condition
# as a tuple of lists
# each list gives locations at one dimension

print(np.where(a>2))


In [ ]:
# Exercise 1.2.4: change values by conditions

a = np.array([[4,2], [3, 4], [5, 0]])
print("before change:", a)

# if a value >3, set it to 3
a[np.where(a>3)]=3
print("after change:", a)

# binarize the array, 
# if a value>3, set it to 1; otherwise, 0
a = np.array([[4,2], [3, 4], [5, 0]])
print("Binarized array:", np.where(a>3, 1, 0))

### 1.3. Array Math

- Basic mathematical functions operate **elementwise** on arrays, and are available both as operator overloads and as functions in the numpy module
- Pay attention to the difference between **elementwise product** and **dot product**

In [ ]:
# Exercise 1.3.1: array addition

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
print (x + y)
print (np.add(x, y))

In [ ]:
# Exercise 1.3.2: Subtraction

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

#Elementwise difference; both produce the array
print (x - y)
print (np.subtract(x, y))

In [3]:
# Exercise 1.3.3:  Elementwise product

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print (x * y)
print (np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [4]:
# Exercise 1.3.4:  dot product

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

np.dot(x, y)
x.dot(y)

# compare the result with Exercise 1.3.3

array([[19, 22],
       [43, 50]])

array([[19, 22],
       [43, 50]])

In [ ]:
# Exercise 1.3.4:  Elementwise division

print (x / y)
print (np.divide(x, y))


In [ ]:
# Exercise 1.3.5:  Elementwise square/square root
x = np.array([[1,2],[3,4]])
np.sqrt(x)

### 1.4. Other useful array functions

- Numpy provides many useful functions for performing computations on arrays
    - **sum/mean/min/max/std**  along different dimensions
    - **transpose**
    - ** reshape **
    - ** sort ** and **argsort**

In [5]:
# Exercise 1.4.1:  array sum/mean/max/min/std

x = np.array([[1,2],[3,4],[3,5]])
x
# Compute sum of all elements; prints "10"
print ("sum of all elements:",np.sum(x))  

# Compute sum of each column
# return 1-dimension array
print ("sum of each column:", np.sum(x, axis=0))  

# Compute sum of each row
# return 1-dimension array
print ("sum of each row:", np.sum(x, axis=1))  

# Compute sum of each row
# return 2-dimension matrix
row_sum_matrix=np.sum(x, axis=1, keepdims=True)
print ("row sum matrix:", row_sum_matrix ) 
print ("row sum matrix shape:", row_sum_matrix.shape )


array([[1, 2],
       [3, 4],
       [3, 5]])

sum of all elements: 18
sum of each column: [ 7 11]
sum of each row: [3 7 8]
row sum matrix: [[3]
 [7]
 [8]]
row sum matrix shape: (3, 1)


In [6]:
# Exercise 1.4.2:  Array transpose
x = np.array([[1,2],[3,4],[5,6]])
print("shape of x:", x.shape)
print ("transpose of x:", x.T)
print("shape of the transpose of x:", x.T.shape)

shape of x: (3, 2)
transpose of x: [[1 3 5]
 [2 4 6]]
shape of the transpose of x: (2, 3)


In [7]:
# Exercise 1.4.2:  Array reshape

x = np.array([[1,2],[3,4],[5,6]])

# reshape it to 2x3 matrix
print("reshape to 2x3 matrix:", np.reshape(x, (2,3)))
# note that this is different from transpose

# flatten the matrix into 1-dimension array
print ("flatten x:", np.reshape(x, -1))

reshape to 2x3 matrix: [[1 2 3]
 [4 5 6]]
flatten x: [1 2 3 4 5 6]


In [9]:
# Exercise 1.4.3:  Array sort 

x = np.array([[8,2],[3,4],[5,2]])

# sort each row of the matrix
print(np.sort(x))

# sort each column of the matrix
print(np.sort(x, axis=0))

# how to sort in descending order?

np.sort(x, axis=0)[::-1,:]

[[2 8]
 [3 4]
 [2 5]]
[[3 2]
 [5 2]
 [8 4]]


array([[8, 4],
       [5, 2],
       [3, 2]])

In [12]:
# Exercise 1.4.4:  Array argsort

x = np.array([[8,2,5,6,1],[3,4,1,2,6]])
x
# sort each row and return the **original value index**
# in an array of the same shape as x
x1=np.argsort(x)
print(x1)

# How can this function be useful?

# how to find where the top 3 values in each row are? 
x1[:,::-1][:,0:3]
# how to find where the top 1 value in each column is?


array([[8, 2, 5, 6, 1],
       [3, 4, 1, 2, 6]])

[[4 1 2 3 0]
 [2 3 0 1 4]]


array([[0, 3, 2],
       [4, 1, 0]])

In [22]:
# Exercise 1.4.5: Term-Frequency Matrix:
# each row is a document
# each column is a word
# value at [i,j] is the count of word j in document i

tf=np.array([[0,2,0,1,2], [1,0,4,0,2], [0,2,3,1,2]])

# 1. Count total occurrences of each word
np.sum(tf, axis=0)
# 2. Fill the term-frequency matrix 
#    with binary values (1: present, 0: not present)
x=np.where(tf>0,1,0)
x
# 3. count document frequency of each word 
#    i.e. the number of documents that contain the word
np.sum(x, axis=0)
# 4. Find the most frequent word in each document
y=np.argsort(tf)
tf
y
y[:,::-1][:,0:3]

array([1, 4, 7, 2, 6])

array([[0, 1, 0, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1]])

array([1, 2, 2, 2, 3])

array([[0, 2, 0, 1, 2],
       [1, 0, 4, 0, 2],
       [0, 2, 3, 1, 2]])

array([[0, 2, 3, 1, 4],
       [1, 3, 0, 4, 2],
       [0, 3, 1, 4, 2]])

array([[4, 1, 3],
       [2, 4, 0],
       [2, 4, 1]])

### 1.5. Broadcasting
- Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations
- Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.
- Examples:
    - add/subtract a constant vector to each row of a matrix 
        * e.g. during data normalization, subtract each samples by mean vector
    - multiply/divide each row of matrix by a vector (1-dimension array)
        * e.g. divide sample by std vector   
- It would be very inefficient to use a loop to achieve this given a large matrix


In [23]:
# Exercise 1.5.1:  Successful broadcasting

# Add the vector B to each row of A

import time

A = np.random.random((10000,4))
B = np.array([0.2,0.1,0.04,0.03])

# By loop:
Z=np.zeros((10000,4))

start=time.time()   # get starting time
for idx in range(A.shape[0]):
    Z[idx]=A[idx]+B
print("time used: %.4f ms"%(time.time()-start))
Z[0]

# By Broadcasting
start=time.time()
Z = A + B
print("time used: %.4f ms"%(time.time()-start))
Z[0]

time used: 0.0137 ms


array([ 0.92725506,  1.04598962,  0.21844353,  0.47926389])

time used: 0.0004 ms


array([ 0.92725506,  1.04598962,  0.21844353,  0.47926389])

In [24]:
# Exercise 1.5.2:  Failed broadcasting

# Add a vector to each column of A
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
B = np.array([1, 0, 1, 4])
Z = A + B  
print (Z)


ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

### 1.6. Broadcasting Rules:
1. Assume two arrays A and B. 
   - <font color='blue'>For example, A has size(10000, 4), B has size (4,). A has rank 2, and B has rank 1</font>
2. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
    - <font color='blue'>Padding 1 to the left of the shape of B. So B's shape becomes (1,4)</font>
3. The two arrays are said to be **compatible** in a dimension **if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension**. If compatible, continue to Step 4; otherwise stop and raise an error
    
    - <font color='blue'> Compare the shapes of A and B in each dimension: </font>
       * <font color='blue'>Dimension 1: A is 10000 and B is 1 => compatible </font>   
       * <font color='blue'> Dimension 2: A is 4 and B is 4 => compatible</font> 
    - <font color='blue'> So, A and B are compatible in every dimension</font>
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
    - <font color='blue'> After brodcasting, B's shape => (10000,4)</font>
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension
    - <font color='blue'> Suppose B=([1, 0, 1]). After broadcasting, B => ([1, 0, 1],[1, 0, 1],...)</font>
6. Apply array math using B after broadcasting

In [25]:
# Exercise 1.5.3:  revisit Exercise 1.5.3

# Add a vector to each column of A
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
B = np.array([1, 0, 1, 4])

# A's shape (4,3), B's shape (1,4)
# It's incompatible with A at the 2nd dimension

# However, after transpose A
# they are compatible
Z = A.T + B  
print (Z.T)

[[ 2  3  4]
 [ 4  5  6]
 [ 8  9 10]
 [14 15 16]]


In [28]:
# Exercise 1.5.4: Compute squared sample error (SSE)
# d is the sample matrix where each row is a sample
# SSE=(d-mean(d))^2

d=np.random.randint(0,10,(100,5))  # populate random numbers between 0 and 10 in an array of size (100, 5)

m=np.mean(d, axis=0)
m.shape
np.sum(np.square(d-m))
np.sum((d-m)*(d-m))

(5,)

4086.5599999999999

4086.5599999999999

## 2. Sparse Matrix
- Why sparse matrix
    * In some matrixes (e.g. document-term matrix), most of the elements are zero. These matrices are called **sparse matrices**, while the ones that have mostly non-zero elements are called **dense matrices**.
    * These matrixes usually are very big. It needs memory to store every number
- Sparse matrix: a matrix that **only stores non-zero elements**. 
- Scipy package provides different types of sparse matrix. Commonly used types:
    * csc_matrix: Compressed Sparse Column format
    * csr_matrix: Compressed Sparse Row format
- Sparse matrixes can be manipulated almost in the same way as a dense matrix. Check https://docs.scipy.org/doc/scipy/reference/sparse.html for functions for sparse matrixes.

In [30]:
# Exercise 2.1: Define a sparse matrix

import numpy as np
from scipy.sparse import csr_matrix
A = csr_matrix([[1, 0, 0], [0, 0, 3], [4, 0, 5]])
print(A)
print(A[1,2])
A.shape

  (0, 0)	1
  (1, 2)	3
  (2, 0)	4
  (2, 2)	5
3


(3, 3)

In [ ]:
# Exercise 2.2: Sparse matrix math

A = csr_matrix([[1, 0, 0], [0, 0, 3], [4, 0, 5]])
v = np.array([1, 0, -1])
A.dot(v)